checks:
  php: true

tools:
  external_code_coverage:
    runs: 8    # Scrutinizer will wait for this many code coverage submissions
    timeout: 600    # Timeout in seconds.

filter:
  excluded_paths:
    - 'features/'
    - 'tests/'

build:
  environment:
    # Languages
    php:
      version: "8.0"
      ini:
        memory_limit: "-1"

  tests:
    override:
      - php-scrutinizer-run
